Repository oda-hub/oda_api, pull requests merged in 2023-09, with the labels that each got.

#208 json from stdlib instead of flask
  oda_api/json.py
Labels: bug, test-live

#209 almost empty rtd config
  .readthedocs.yaml
Labels: test-live

#213 remove scripts
  setup.py
Labels: test-live

#214 Update setup.cfg
  setup.cfg
Labels: test-live

#215 specialized methods
  .github/workflows/python-package.yml
  .pylintrc
  oda_api/gallery_api.py
  tests/test_drupal.py
Labels: test-live, product-gallery
